export const sounds = {
  isabellaBreatheIn: require("../../assets/audio/isabella_inhale.mp3"),
  isabellaBreatheOut: require("../../assets/audio/isabella_exhale.mp3"),
  isabellaHold: require("../../assets/audio/isabella_hold.mp3"),
  jamesonBreatheIn: require("../../assets/audio/jameson_inhale.mp3"),
  jamesonBreatheOut: require("../../assets/audio/jameson_exhale.mp3"),
  jamesonHold: require("../../assets/audio/jameson_hold.mp3"),
  claraBreatheIn: require("../../assets/audio/clara_inhale.mp3"),
  claraBreatheOut: require("../../assets/audio/clara_exhale.mp3"),
  claraHold: require("../../assets/audio/clara_hold.mp3"),
  marcusBreatheIn: require("../../assets/audio/marcus_inhale.mp3"),
  marcusBreatheOut: require("../../assets/audio/marcus_exhale.mp3"),
  marcusHold: require("../../assets/audio/marcus_hold.mp3"),
  endingBell: require("../../assets/audio/endingbell1.mp3"),
  cueBell1: require("../../assets/audio/cuebell1.mp3"),
  cueBell2: require("../../assets/audio/cuebell2.mp3"),
  frequency852hz: require("../../assets/audio/852hz.mp3"),
  frequency777hz: require("../../assets/audio/777hz.mp3"),
  frequency432hz: require("../../assets/audio/432hz.mp3"),
};
